---
title: "01_data"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

This script prepares and verifies the data for analysis of the Interpersonal Needs Questionnaire-15 (INQ-15).

# Packages
```{r packages}
if (!require("readxl")) {
  install.packages("readxl")
  require("readxl")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
```

# Data
```{r Load datasets}
Data1 <- read_xlsx("Raw_data/863_raw_data.xlsx")
colnames(Data1)
# this contains 863 participants with 15 INQ items 
## _r = reverse scored
## _rU = unrecoded reversed

# Make a folder to save the output
if (!dir.exists("01_output")) {
  dir.create("01_output")
}
```

# Item descriptives
```{r descriptives}
Baseline_summary <- psych::describe(Data1 %>%
  dplyr::select(INQ_1, 
                INQ_2, 
                INQ_3, 
                INQ_4, 
                INQ_5, 
                INQ_6, 
                INQ_7_r, 
                INQ_8_r, 
                INQ_9, 
                INQ_10_r,
                INQ_11,
                INQ_12, 
                INQ_13_r, 
                INQ_14_r, 
                INQ_15_r

  )) 

View(Baseline_summary)

# Save the table
write.csv(Baseline_summary,
  file = paste0(
    "01_output/Descriptives_baseline_",
    format(Sys.Date(), "%Y-%m-%d"), ".csv"
  ),
  row.names = TRUE
)
```

# INQ-15 validity check
```{r score check}
# Check that reversed and unreversed match
rev_pairs <- list(
  INQ_7  = c("INQ_7_r", "INQ_7_rU"),
  INQ_8  = c("INQ_8_r", "INQ_8_rU"),
  INQ_10 = c("INQ_10_r", "INQ_10_rU"),
  INQ_13 = c("INQ_13_r", "INQ_13_rU"),
  INQ_14 = c("INQ_14_r", "INQ_14_rU"),
  INQ_15 = c("INQ_15_r", "INQ_15_rU")
)

rev_check <- lapply(rev_pairs, function(vars) {
  r  <- Data1[[vars[1]]] # recoded items
  ru <- Data1[[vars[2]]] # unrecoded items
  
  data.frame(
    all_match = all(r == (7 + 1 - ru), na.rm = TRUE),
    n_mismatch = sum(r != (7 + 1 - ru), na.rm = TRUE)
  )
})

do.call(rbind, rev_check)
```

# SBQ-R check
```{r sbqr check}
table(Data1$SBQ001)
table(Data1$SBQ001_scored)

table(Data1$SBQ002)
table(Data1$SBQ002_scored)

table(Data1$SBQ003)
table(Data1$SBQ003_scored)

table(Data1$SBQ004)
table(Data1$SBQ004_scored)

table(Data1$SBQtotal)

# Make a new total score to verify
Data1 <- Data1 %>%
  mutate(
    SBQ_R_total_check = SBQ001_scored + SBQ002_scored + SBQ003_scored + SBQ004_scored
  )

summary(Data1$SBQtotal)
summary(Data1$SBQ_R_total_check)

# Make a new binary suicide risk variable to verify; anyone >6 = 1 on SBQR_total_check
Data1 <- Data1 %>%
  mutate(
    sui_risk_check = case_when(
      is.na(SBQ_R_total_check) ~ NA_real_,
      SBQ_R_total_check > 6 ~ 1,
      SBQ_R_total_check <= 6 ~ 0
    )
  )

table(Data1$sui_risk_check)
table(Data1$sui_risk)
```

# Save dataset
```{r save}
write.csv(Data1,
  file = paste0(
    "01_output/863_scored_data.csv"
  ),
  row.names = TRUE
)
```

